CLASS zbp_27d_i_trip_attach DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF y27d_i_trip_attach.
protected section.
private section.
ENDCLASS.



CLASS ZBP_27D_I_TRIP_ATTACH IMPLEMENTATION.
ENDCLASS.
